lib/embed_chat_web/router.ex
defmodule EmbedChatWeb.Router do
  use EmbedChatWeb, :router

  if Mix.env == :pod do
    use Plug.ErrorHandler
    use Sentry.Plug
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug EmbedChatWeb.UserPlug
    plug EmbedChatWeb.UserTokenPlug
    plug EmbedChatWeb.UserAddressPlug, repo: EmbedChat.Repo
  end

  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials seperate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
    plug Guardian.Plug.LoadResource, key: :admin
    plug EmbedChatWeb.AdminPlug
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EmbedChatWeb.Locale, "en"
    plug EmbedChatWeb.SDK, repo: EmbedChat.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EmbedChatWeb do
    pipe_through [:browser, :browser_auth, :impersonation_browser_auth]

    get "/", PageController, :index
    get "/price", PageController, :price
    get "/welcome", PageController, :welcome

    resources "/users", UserController, only: [:index, :new, :create, :show, :edit, :update]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/rooms", RoomController
    resources "/attempts", AttemptController
    resources "/auto_message_configs", AutoMessageConfigController
    resources "/messages", MessageController
    resources "/projects", ProjectController
    resources "/addresses", AddressController, only: [:show, :index]
    resources "/news", NewsController
  end

  pipeline :admin_layout do
    plug :put_layout, {EmbedChatWeb.LayoutView, :admin}
  end

  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", EmbedChatWeb.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth, :admin_layout]

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    post "/impersonate/:user_id", SessionController, :impersonate, as: :impersonation
    delete "/impersonate", SessionController, :stop_impersonating
    resources "/users", UserController
  end

  scope "/manage", EmbedChatWeb do
    # resources "/chats", VideoController
  end

  # Other scopes may use custom stacks.
  scope "/api", EmbedChatWeb do
    pipe_through [:api, :api_auth]

    resources "/visitors", VisitorController, except: [:new, :edit]
    resources "/message_mailers", MessageMailerController, only: [:create]
    resources "/tracks", TrackController, except: [:new, :edit]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end
end

lib/embed_chat_web/views/layout_view.ex
defmodule EmbedChatWeb.LayoutView do
  use EmbedChatWeb, :view

  # TODO support params
  def current_locale_path(conn, locale) do
    conn.request_path <> "?locale=#{locale}"
  end

  # TODO support params
  def current_locale_url(conn, locale) do
    EmbedChatWeb.Router.Helpers.url(conn) <> conn.request_path <> "?locale=#{locale}"
  end
end

lib/embed_chat_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= gettext "Lewini Live Chat: A Live Chat Software for Business!" %></title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.cyan-blue.min.css" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="alternate" hreflang="en" href=<%= current_locale_url(@conn, "en") %> />
    <link rel="alternate" hreflang="ja" href=<%= current_locale_url(@conn, "ja") %> />
    <%= render "track.html" %>
  </head>

  <body>
    <!-- Always shows a header, even in smaller screens. -->
    <!-- <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer"> -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Lewini</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= if @admin do %>
              <%= link gettext("Home"),   to: admin_user_path(@conn, :index), class: "mdl-navigation__link" %>
              <%= link gettext("Users"),  to: admin_user_path(@conn, :index), class: "mdl-navigation__link" %>
              <%= link gettext("Logout"), to: admin_session_path(@conn, :delete, @admin), method: :delete, class: "mdl-navigation__link" %>
            <% else %>
              <%= link gettext("Home"),   to: admin_user_path(@conn, :index), class: "mdl-navigation__link" %>
              <%= link gettext("Login"),  to: admin_session_path(@conn, :new), class: "mdl-navigation__link" %>
            <% end %>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
          <!-- Your content goes here -->
          <%= if get_flash(@conn, :info) || get_flash(@conn, :error) do %>
            <center>
              <p>
                <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
                <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
              </p>
            </center>
          <% end %>
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>
    </div>

    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/embed_chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= gettext "Lewini Live Chat: A Live Chat Software for Business!" %></title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-blue.min.css" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="alternate" hreflang="en" href=<%= current_locale_url(@conn, "en") %> />
    <link rel="alternate" hreflang="ja" href=<%= current_locale_url(@conn, "ja") %> />
    <%= render "track.html" %>
  </head>

  <body>
    <!-- Always shows a header, even in smaller screens. -->
    <!-- <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer"> -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Lewini</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= if @current_user do %>
              <%= render "header_login_nav.html", conn: @conn, current_user: @current_user %>
            <% else %>
              <%= render "header_nologin_nav.html", conn: @conn %>
            <% end %>
          </nav>

          <!-- Right aligned menu below button -->
          <button id="menu-lower-right"
            class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
            for="menu-lower-right">
            <li class="mdl-menu__item">
              <%= link gettext("English"), to: current_locale_path(@conn, "en"), class: "mdl-button mdl-js-button" %>
            </li>
            <li class="mdl-menu__item">
              <%= link gettext("Japanese"), to: current_locale_path(@conn, "ja"), class: "mdl-button mdl-js-button" %>
            </li>
          </ul>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <%= if @current_user do %>
          <span class="mdl-layout-title">
            <%= @current_user.email %>
          </span>
          <nav class="mdl-navigation">
            <%= render "header_login_nav.html", conn: @conn, current_user: @current_user %>
          </nav>
        <% else %>
          <span class="mdl-layout-title">
            Lewini
          </span>
          <nav class="mdl-navigation">
            <%= render "header_nologin_nav.html", conn: @conn %>
          </nav>
        <% end %>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
          <!-- Your content goes here -->
          <%= if get_flash(@conn, :info) || get_flash(@conn, :error) do %>
            <center>
              <p>
                <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
                <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
              </p>
            </center>
          <% end %>
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>
    </div>

    <div data-id="<%= @conn.assigns[:chat_id] %>" id="lewini-chat"></div>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script>window.userAddress = "<%= assigns[:user_address] %>"</script>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://cdn.ravenjs.com/3.9.1/raven.min.js" crossorigin="anonymous"></script>
    <script>Raven.config('https://13f465e7ecb948afbe73f9f7a5f43f94@sentry.io/98951').install();</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/embed_chat_web/templates/layout/email.html.eex
<html>
  <head>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/embed_chat_web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>

lib/embed_chat_web/templates/layout/header_login_nav.html.eex
<%= link gettext("Home"),         to: page_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Messages"),     to: message_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Auto Message"), to: auto_message_config_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Setup"),        to: project_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Account"),      to: user_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Logout"),       to: session_path(@conn, :delete, @current_user), method: :delete, class: "mdl-navigation__link" %>
<%= if admin_logged_in?(@conn) do %>
  <%= link gettext("Stop Impersonating"),
           to: admin_session_path(@conn, :stop_impersonating),
           method: :delete,
           class: "mdl-navigation__link"
  %>
  <%= link gettext("Attempts"),
           to: attempt_path(@conn, :index),
           class: "mdl-navigation__link"
  %>
<% end %>

lib/embed_chat_web/templates/layout/header_nologin_nav.html.eex
<%= link gettext("Home"),     to: page_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Release Notes"), to: news_path(@conn, :index), class: "mdl-navigation__link" %>
<%= link gettext("Price"),    to: page_path(@conn, :price), class: "mdl-navigation__link" %>
<%= link gettext("Login"),    to: session_path(@conn, :new), class: "mdl-navigation__link" %>
<%= link gettext("Register"), to: user_path(@conn, :new), class: "mdl-navigation__link" %>

lib/embed_chat_web/templates/layout/track.html.eex
<!-- start Mixpanel -->
    <script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
       for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
     mixpanel.init("426ecf95068c318c25f7aa80ab5b8541");
     mixpanel.track("Page view");
    </script>
<!-- end Mixpanel -->